<?php
// module/Account/view/account/account/add.phtml:
$title = 'Account xxxxxx';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<pre>
<?php
$form->setAttribute('action', $this->url('account', array(
    'action' => 'add'
)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</pre>