<?php
// module/Account/view/account/account/delete.phtml:
$title = 'Account a';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>AccountAccountAccountAccountAccountAccount
   '<?php echo $this->escapeHtml($account->artist); ?>' artist
   '<?php echo $this->escapeHtml($account->title); ?>' title
</p>
<?php
$url = $this->url('account', array(
    'action' => 'delete',
    'id' => $this->id
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="hidden" name="id"
			value="<?php echo (int) $account->id; ?>" /> <input type="submit"
			name="del" value="del" /> <input type="submit" name="del"
			value="submit" />
	</div>
</form>