<?php
// module/Album/view/album/album/index.phtml:
$title = '我的唱片';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
   <a href="<?php echo $this->url('album', array('action'=>'add'));?>">添加新唱片</a>
</p>
<table class="table">
<tr>
   <th>名称</th>
   <th>艺术家</th>
   <th>操作</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
   <td><?php echo $this->escapeHtml($album->title);?></td>
   <td><?php echo $this->escapeHtml($album->artist);?></td>
   <td>
       <a href="<?php echo $this->url('album',
           array('action'=>'edit', 'id' => $album->id));?>">编辑</a>
       <a href="<?php echo $this->url('album',
           array('action'=>'delete', 'id' => $album->id));?>">删除</a>
   </td>
</tr>
<?php endforeach; ?>
</table>