<?php
// module/Helloworld/view/helloworld/helloworld/index.phtml:
$title = 'Helloworld $title';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php echo $this->url('helloworld', array('action'=>'add'));?>">AAAAAAAAAAAAAAAAAAAA</a>
</p>
<table class="table">
	<tr>
		<th>xxxxx</th>
		<th>qqqqq</th>
		<th>fffffffffffff</th>
	</tr>
<?php foreach ($helloworlds as $helloworld) : ?>
<tr>
		<td><?php echo $this->escapeHtml($helloworld->title);?></td>
		<td><?php echo $this->escapeHtml($helloworld->artist);?></td>
		<td><a
			href="<?php
    echo $this->url('helloworld', array(
        'action' => 'edit',
        'id' => $helloworld->id
    ));
    ?>">edit</a> <a
			href="<?php
    
    echo $this->url('helloworld', array(
        'action' => 'delete',
        'id' => $helloworld->id
    ));
    ?>">delete</a></td>
	</tr>
<?php endforeach; ?>
</table>